#! bin/bash

# Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
cp -R ./zsh/oh-my-zsh ~/.oh-my-zsh

# Sym link dotfiles
ln -sv “~/.dotfiles/zsh/.zshrc ~
ln -sv “~/.dotfiles/git/.gitconfig ~
ln -sv “~/.dotfiles/git/.gitignore ~

# Install Xcode CLI
xcode-select --install